### ISSUE TITLE
Run plugins on numpy arrays as input image in headless mode

### ISSUE THREAD

**Issue by ma-sadeghi** [imagej/pyimagej#126]
I know how to convert a numpy array into a dataset, but I don't know how to "pass" this dataset to a plugin. Sorry for the very basic question. When I run:
```python
plugin = 'Mean'
args = {'block_radius_x': 10, 'block_radius_y': 10}
ij.py.run_plugin(plugin, args)
```
it complains that
```bash
[java.lang.Enum.toString] Macro Error: There are no images open in line 1
```
My question is, how do I load my numpy array into `pyimagej` (in headless mode), so that I can run a plugin on the image?

**Comment by ctrueden** [comment]
Running ImageJ 1.x commands in headless mode is tricky. See also #51 and #97, which are likely the same issue.

I was experimenting a few months ago with ways to make this work while in headless mode (https://github.com/imagej/i2k-2020-pyimagej/commit/56199778023465a95c595dbcc06eacf3ad5c0681), but I never finished working it all out and polishing it.

Since this is the most common problem people are reporting with PyImageJ, getting this better supported and documented is relatively urgent.

**Comment by ma-sadeghi** [comment]
Thank you for your reply. Is there an equivalent command in ImageJ 2.x (that can be run in headless mode)? Thanks :)

**Comment by imagejan** [comment]
@ma-sadeghi you might try calling `ops.filter.mean` from ImageJ Ops:

```
import jpype.imports
from net.imglib2.algorithm.neighborhood import RectangleShape

output = ij.op().create().img(input)
ij.op().filter().mean(output, input, RectangleShape(10, False))
```

I'm not sure about the exact shape of the mean filter kernel with the original integral image filter you were using, but you can play with the `Shape` input as required.

**Comment by Nicholas-Schaub** [comment]
Hey all. I just came across this. We are trying to run a somewhat generic ImageJ macro executor for a platform we are creating at NIH. We just ran into the exact same issue described in your Notebook @ctrueden. We independently replicated basically what you had in your Notebook, but every iteration we attempted (including using input parameters and converting to ImagePlus) never seemed to register the image with ImageJ. At the end of the day, as you mention in your Notebook, there seemed to be a fundamental problem with images not getting registered with the WindowManager.

I'm glad this has been marked urgent. If there is anything me or my team can do to assist you, I am more than happy to assist. We were about to attempt more extreme measures (e.g. a very custom solution), but since this appears like it will be worked on we are happy to coordinate with you in any way we can. One way or another we are determined to get this to work, because many of our users have requested the ability to execute their ImageJ macros on our platform.

**Comment by NicolasCristini** [comment]
> Hi all, as @ctrueden said: "Running ImageJ 1.x commands in headless mode is tricky." 
I tried to complete a image analysis with PyimageJ for my project: [IPAN](https://github.com/NicolasCristini/ImageJ-Processing-Assistant-Notebook) I hope that the example notebooks I published can be useful. Please, contact me if have any question or comment. Thanks

**Comment by Nicholas-Schaub** [comment]
> In the first two notebooks I show how to work with ImageJ from the notebook in headless mode. I hope it can be be useful! Please, contact me if have any question or comment. Thanks

@NicolasCristini , thanks for sharing. We too have discovered that you can open the files using a macro, but that is also the problem and the reason why this is an open issue in our opinion. For us, we have a need to open the files using our own image reader to properly capture metadata. Even outside of our specific use case, I can imagine situations where people want to use ImageJ ops for specific operations on an image/matrix in memory.

The main issue seems to be that ImageJ 1.X handles image awareness through the window manager, which you don't ever get in headless mode. It sounds like some progress is being made on it though :)

Also, if there is any way that me and my team could contribute to a solution or testing, we would be more than happy to help. We have created an ImageJ op generation pipeline that generates Python code to run ImageJ ops from a Docker container. We are happy to share any of this if anyone is interested.

**Comment by ctrueden** [comment]
I finally dug deeply on this issue. It turns out that `run_plugin` was constructing a macro and then running it with `run_macro`! This is not at all what `run_plugin` should have been doing, which is calling `IJ.run`.

**Comment by Nicholas-Schaub** [comment]
I laugh because I have been there...with my own code even. Thanks for running this down. I have many people that have been asking us about this in the pipelines we are building with pyimagej.

**Comment by Nicholas-Schaub** [comment]
Wait, is there still the issue of running macros on an open image in headless mode if the image is not opened by the macro itself?

**Comment by ctrueden** [comment]
@Nicholas-Schaub wrote:
> is there still the issue of running macros on an open image in headless mode if the image is not opened by the macro itself?

Yes, unfortunately: #97. But I just played with it, and might have solved it: https://github.com/imagej/pyimagej/issues/97#issuecomment-1113919519.

**Comment by Nicholas-Schaub** [comment]
We will try it out. Maybe we can provide some additional debug info.

**Comment by ctrueden** [comment]
@Nicholas-Schaub It's rife with peril, but I got it working! See [this Jupyter notebook](https://github.com/imagej/i2k-2022-pyimagej/blob/9e23cce2d0c5260dfe0bdeb7e98bcd27608f87df/I2K-2022-PyImageJ-Workshop.ipynb) section 9.5. There's a hack to prime the pump, and then you can start registering `ImagePlus` objects via the `show()` function.
