### ISSUE TITLE
Support conversion of `RealMask` ROI types to/from NumPy arrays

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#128]
And do it how napari does it for its shapes layers.

**Comment by gselzer** [comment]
So, I think this is a tough one.

There are a couple points of discussion:
1. @ctrueden says: "And do it how napari does it for its shapes layers." As napari's `Shapes` layer stores its data as sets of vertices, I'd argue the converters should go in napari-imagej, **not** in pyimagej. The backing data will not make any sense in pyimagej.
2. napari [`Shapes`](https://napari.org/api/stable/napari.layers.Shapes.html) layers would technically be equivalent to a `List<RealMask>`. So, while it is easy to add `RealMask` to `Shapes` conversions, you would require only one shape to make a `Shapes` to `RealMask` conversion (otherwise you'd have to return a `List<RealMask>`. Now, our converters *could* do that, due to the "wild west" that is Python typing, but that seems like a code smell to me.
3. napari only supports a set of shapes (line, rectangle, ellipse, path, polygon). This covers most of our needs, but it does not allow the freedom that the backing `Predicate` allows.

So, without any development, I think we can support:
* Conversion of `Shapes` layers with *one* shape to a `RealMask`.
* Conversion of `Shapes` layers with *multiple* shapes to a `List<RealMask>`.
* Conversion of select `RealMask` implementations to `Shapes` layers.

cc @jni

**Comment by imagejan** [comment]
How about `Shapes <=> net.imagej.roi.ROITree`, similar to the IJ1-IJ2 `Overlay <=> ROITree` conversions?
Otherwise, I'd be in favor to _always_ return a list, even when there's only one shape.

**Comment by gselzer** [comment]
> How about `Shapes <=> net.imagej.roi.ROITree`, similar to the IJ1-IJ2 `Overlay <=> ROITree` conversions?

Hmm, I suppose that in theory I'd be on board @imagejan. At the end of the day though, I think that the conversions should go to the type most expected. Do you think that `ROITree` would be most expected? What if there is only one shape in the `Shapes` layer?

One thing I'm rather naive on: what do many ImageJ modules/Commands expect? As far as Ops go, they all expect a ROI (with most taking a `Polygon2D`). If we have a `Shapes` layer with a single polygon, I'd expect that I could pass it to one of these Ops taking a `Polygon2D`...

**Comment by ctrueden** [comment]
I am on board with putting the ROI converter(s) in napari-imagej rather than PyImageJ, since there is no Python-equivalent ROI library.

As for types: I prefer the consistency of always converting to/from `ROITree`. If you know you only have one shape, it's easy to unwrap. Let's keep it simple for now, and see how the initial implementation goes.

**Comment by gselzer** [comment]
> I am on board with putting the ROI converter(s) in napari-imagej rather than PyImageJ, since there is no Python-equivalent ROI library.

Sounds good!

> As for types: I prefer the consistency of always converting to/from `ROITree`. If you know you only have one shape, it's easy to unwrap. Let's keep it simple for now, and see how the initial implementation goes.

Sure, but if we do that, how can we call the Ops that take a single `ROI`?

> As for the ROI types that napari does not support: that is a tougher one. We may need to fall back to using labelings for more complex and/or custom shapes.

See [this conversation with @jni](https://napari.zulipchat.com/#narrow/stream/212875-general/topic)/Defining.20Arbitrary.20Shapes/near/271899269

**Comment by ctrueden** [comment]
> how can we call the Ops that take a single `ROI`?

My naive answer to that is `org.scijava.convert.Converter` plugins. But in practice I'm sure there will be wrinkles...

**Comment by gselzer** [comment]
> My naive answer to that is `org.scijava.convert.Converter` plugins. But in practice I'm sure there will be wrinkles...

The converters are implemented in https://github.com/imagej/imagej-common/pull/101
