### ISSUE TITLE
Add flag to control imagej-legacy endpoint

### ISSUE THREAD

**Issue by hinerm** [imagej/pyimagej#139]
We currently aggressively add imagej-legacy[1](https://github.com/imagej/pyimagej/blob/ccdcc0dd82071a83aaa842cdc3ab2d98444658cb/imagej/__init__.py#L154),[2](https://github.com/imagej/pyimagej/blob/ccdcc0dd82071a83aaa842cdc3ab2d98444658cb/imagej/__init__.py#L125) as an endpoint. This is often unnecessary (e.g. initializing a Fiji endpoint).

Instead, let's add a flag for including legacy mode and default it to `False` - giving the user what they ask for, instead of always adding extra "stuff.

**Comment by hinerm** [comment]
@ctrueden why would we have a flag for legacy mode? If it's just a matter of adding `imagej-legacy` to the init string, why are we treating it differently than any other endpoint..?

**Comment by ctrueden** [comment]
The main questions are: what should the default behavior be? And how should non-default behavior be enabled as easily as possible?

When people say they want to "use ImageJ from Python", do they mean ImageJ, or do they mean ImageJ2? And do they understand the difference?

Without having polled it scientifically, I believe there is a sizable population that is most interested in doing things with the original ImageJ, and would thus prefer imagej-legacy included by default. And a less sizable, but still probably significant, fraction of users want "pure ImageJ2" without the original ImageJ—at least some of the time. And of course yet other users want Fiji.

So what should the default be?
1. Pure ImageJ2 (i.e. `net.imagej:imagej`)
2. ImageJ2+ImageJ (i.e. `net.imagej:imagej+net.imagej:imagej-legacy`)
3. Fiji (i.e. `sc.fiji:fiji`)

I would like to exclude Fiji as default immediately, because this is not the PyFiji project, and there are other uses of ImageJ/ImageJ2 besides only Fiji. So that leaves (1) or (2).

The thinking on making ImageJ2+ImageJ the default was two-fold: A) the population of users that want the original ImageJ included in the environment is greater than those who do not; and B) there is a substantial population of users who do not understand the difference between ImageJ2, ImageJ, ImageJ Legacy, and so forth, and want PyImageJ to "just work" for them, including `ij.*` classes and so on.

At the beginning, we had pure ImageJ2 as the default, and for people to enable support for the original ImageJ they had to RTFM to discern the arcane syntax of `imagej.init('net.imagej:imagej+net.imagej:imagej-legacy')`—it was not something you could figure out intuitively from parameter names alone. So we changed it to "ImageJ Legacy included by default" (at least I _think_ we changed it?), since the audience who might want "pure ImageJ2" is both smaller and more tech-savvy than the audience that wants the original ImageJ, and they can hopefully more often figure out to pass a different Maven coordinate.

Still, since PyImageJ is designed around both ImageJ2 and the original ImageJ, it would be ideal for the `init` function to have a built-in flag for controlling whether ImageJ Legacy is included in the environment. This eliminates possible confusion over whether `init` is bringing in the legacy stuff, because there is a shortcut flag for explicitly controlling that. I think it's much nicer than asking anyone to give an explicit Maven coordinate for either of these primary cases we are trying to support.

Does that answer your question? Or maybe to answer it in a TL;DR way:

> why are we treating it differently than any other endpoint.

Convenience. Discoverability. Simplicity. Because PyImageJ's primary purpose is to support both ImageJ2 and the original ImageJ.

**Comment by hinerm** [comment]
@ctrueden I had this line in the issue description:

>giving the user what they ask for, instead of always adding extra "stuff."

It sounds like this is *not* actually what we want to do.. instead we do want to treat ImageJ-Legacy specially. But after reading your reasoning I think this original statement was going in the wrong direction:

>flag for including legacy mode and default it to False

I think we *should* create the flag but default it to `True`. I think if it were defaulted to `False` as I had originally written then, from a user perspective, initializing imagej with a parameter `legacyMode=True` feels like just as much work as initializing but adding the `imagej-legacy` endpoint. On the other hand, having `imagej-legacy` always included by default but having a parameter to *remove* feels much more a clear justification for why we would have such a parameter.

**Comment by ctrueden** [comment]
> I think we _should_ create the flag but default it to `True`.

Sounds good, I agree!

> initializing imagej with a parameter `legacyMode=True` feels like just as much work as initializing but adding the `imagej-legacy` endpoint.

I don't think so. I think writing the arcane endpoint syntax is scarier than setting a simple flag.

> On the other hand, having `imagej-legacy` always included by default but having a parameter to _remove_ feels much more a clear justification for why we would have such a parameter.

Makes sense to me. However, we need to be a little careful: doing an endpoint like `sc.fiji:fiji` will already include legacy, and we shouldn't let people turn it off in that case. I think the flag should only have an effect when the endpoint is a plain version like `2.3.0`, or else the full ImageJ2 endpoint syntax `net.imagej:imagej:2.3.0`. But not if the user passes some other thing that has ImageJ2 as a dependency. Does that make sense?
