### ISSUE TITLE
Getting reference to an IJ1 plugin class

### ISSUE THREAD

**Issue by nanthony21** [imagej/pyimagej#146]
I would like to be able to directly access the public methods of a plugin class. However, this plugin is declared in a `plugins.config` file rather than using the ImageJ2-style `@Plugin` annotation. This means that the plugin doesn't appear when using `ij.plugin().getPlugins()`. However I can still run the plugin as a macro using `ij.py.run_macro(...` and building a `str` that will call the macro.

Is there any way that I can still get a reference to the plugin instance like you would with an IJ2 plugin using `ij.plugin().getPlugin("my.plugin.Class")` ?

**Comment by ctrueden** [comment]
@nanthony21 How about just loading the plugin class, instantiating it, and using it directly?
```python
from scyjava import jimport
MyPlugin = jimport("my.plugin.MyPlugin")
myPlugin = MyPlugin() # create an instance
arg = "" # or whatever arguments you want to pass the plugin
myPlugin.run(arg)
myPlugin.someOtherPublicMethod(arg1, arg2, etc)
```

**Comment by nanthony21** [comment]
Thanks!, I wasn't aware of `scyjava.jimport()`. That works perfectly for me.

**Comment by imagejan** [comment]
@ctrueden It should also work using jpype directly, shouldn't it?

```python
import jpype.imports

from my.plugin import MyPlugIn

myPlugIn = MyPlugIn()

...
```

**Comment by ctrueden** [comment]
> It should also work using jpype directly, shouldn't it?

Yep. I just get nervous every time we expose the jpype "transitive dependency" to callers, rather than keeping it encapsulated. Maybe we'll change how it works some day, I don't know! After all, we did switch from pyjnius to jpype, and all those `autoclass` calls didn't work anymore. Whereas we can make sure `jimport` keeps working regardless of the backend.

I was going to write that it's highly unlikely we'll migrate away from JPype. And that's true. But what about supporting the other direction? (Starting a Python runtime from Java) We can't currently use JPype to do that, we'd have to use [jep](https://github.com/ninia/jep). I know @hanslovsky already got some things working in this direction, and the eventual plan is to build on that. The hope would be that we can reuse the same syntax at the scyjava level at least for things like importing classes.
