### ISSUE TITLE
Consider limiting scope of initialization

### ISSUE THREAD

**Issue by hinerm** [imagej/pyimagej#149]
After [a discussion](https://github.com/imagej/pyimagej/commit/c44c0261f7a4fde459da699558fb5c9f1d11482b#r60184665) with @ctrueden I'm worried that `imagej.init` appears to be more general than it really is or should be.

For example, we can initialize with a non-imagej endpoint, which of course fails because ImageJ is not on the classpath:
```
imagej.init('org.apache.commons:commons-lang3:3.12.0`)
```

The project is Py**ImageJ**.. shouldn't ImageJ always be included?

I am also concerned about the possibility of selecting a primary endpoint that does not have `pom-scijava` as a parent.

So my initial proposal, when initializing with a set of endpoints or endpoint string, would be:
* If `net.imagej:imagej` or `sc.fiji:fiji` are present in the given list, make them the primary (prioritizing `fiji`)
* If neither is present, add `net.imagej:imagej:RELEASE` as the primary endpoint
* Add a flag to disable this behavior

**Comment by ctrueden** [comment]
I agree that the scope of PyImageJ should be ImageJ-centric, and we want to convey that. It is assumed that the endpoint given will include `net.imagej:imagej`; otherwise the initialization will fail.

That said, we need to avoid hardcoding Fiji-isms into the PyImageJ codebase. The tool should be extensible to other platforms built on ImageJ2, not just Fiji, with Fiji serving as our dog-fooding exercise for such extensibility.

How about if the add_legacy flag simply always uses `net.imagej:imagej-legacy:MANAGED`? That would work with both of our primary use cases, as well as being extensible to other projects that extend pom-scijava, or otherwise manage `net.imagej:imagej-legacy` the way they want.
