### ISSUE TITLE
Finalize dimension order behavior when converting images between ImageJ2 and xarray

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#151]
NumPy et. al dimension order conventions, as [described in the scikit-image documentation](https://scikit-image.org/docs/dev/user_guide/numpy_images.html): channel is always last, otherwise it's always inverse compared to Java, to allow fast iteration over pixels. Example:
* `(t, pln, row, col, ch)` translates to TZYXC.

ImgLib2 et. al dimension order conventions: XY first, or CXY for interleaved data, followed by the other dims in whatever order.
* XYCZT — The order used by the original ImageJ's hyperstacks.

### Algorithm to go from a Java dims list to a Python dimension order

1. Invert the order: XYCZT &rarr; TZCYX
2. Push Y (if it exists) to the end: TZCYX &rarr;  TZCXY
3. Push X (if it exists) to the end: TZCXY &rarr;  TZCYX
4. Push C (if it exists) to the end: TZCYX &rarr;  TZYXC

Steps 2 and 3 might seem pointless above, but they matter if the Java dimension order has X and Y in unusual places to begin with. For example, if the Java image is TYCXZ, then &rarr;  (1) ZXCYT &rarr; (2) ZXCTY &rarr; (3) ZCTYX &rarr; (4) ZTYXC. :+1:

### Algorithm to go from a Python dims list to a Java dimension order

1. Invert the order: TZYXC &rarr; CXYZT
2. Pull Y to the front: CXYZT &rarr; YCXZT
3. Pull X to the front: YCXZT &rarr; XYCZT

I'm less certain about this Python-to-Java algorithm—maybe we should not do (2) or (3)—but having XY first seems friendlier for certain assumptions in the Java codebase in a few places, especially in the ImageJ2 layer.

See also:
* imglib/imglyb#6
* imagej/pyimagej#17
* https://forum.image.sc/t/53436

**Comment by imagejan** [comment]
Dimension order conventions for `scikit-image` are summarized here:
https://scikit-image.org/docs/dev/user_guide/numpy_images.html

`(t, pln, row, col, ch)` translates to TZYXC.

**Comment by ctrueden** [comment]
@imagejan Thank you, I updated the comment above. I suspected what I was writing was wrong before :wink:, but couldn't find that scikit-image link in a couple minutes of searching.

**Comment by imagejan** [comment]
@ctrueden I always thought that the XYCZT convention was a pure ImageJ-1.x-ism, the default order for `ij.ImagePlus` and hyperstacks. ImageJ2 can handle arbitrary dimensions, similar to xarray in Python, with the axis metadata present to define their meaning. Right?

Why do we need to bake-in XYCZT here?

In my understanding, the differences exist because the iteration order is different in the two worlds: in Java, the fastest iterating comes first, in Python last. So in the absence of metadata defining the axes, shouldn't we always just invert the order of dimensions?

**Comment by ctrueden** [comment]
> Why do we need to bake-in XYCZT here?

We don't... sorry if I gave that impression above. I wrote "XYCZT — The order used by the original ImageJ's hyperstacks." Where "the original ImageJ" here means ImageJ 1.x, not ImageJ2. It was just an example of a well-supported dimension order on the Java side.

**Comment by imagejan** [comment]
That makes sense, @ctrueden, thanks.

I wonder what's the best option from a perspective of performance. On a 1-dimensional pixel array (e.g. those backing `ImagePlus` or `ArrayImg`), a flat iteration order is the fastest, and anything else can have (much?) slower performance.

If you have two RAIs with differing iteration order (e.g. ArrayImg and CellImg), you can always use `Views.flatIterable` to ensure accessing the same pixel positions when iterating, but at a performance cost possibly, right?

So what about the performance if we "arbitrarily" change the order when converting between Java and Python? Did anyone benchmark this already? I would vote for the option with the least performance impact, and offer utility methods for everything on top for convenience.

**Comment by ctrueden** [comment]
No one benchmarked anything yet.

@elevans Maybe we can go over this next Tuesday for our weekly session.

**Comment by elevans** [comment]
Sounds good, I'll continue on my current trajectory and get the some kind of dimension reordering methods worked out.

**Comment by elevans** [comment]
This is how we currently deal with converting between ImgLib2 and Numpy style dimension order.  5D ImgPlus data with dimension order `XYCZT` gets converted to a Numpy array or Xarray with `TZCYX` order which is mostly correct, except that `C` needs to be in the last position. This is because all we do is invert the order. Going the other direction, Numpy style (`TZYXC`) to ImgLib2 style is a little more intelligent. We check if the last dimension is `C` and if so, move the `C` axis to the front: `CTZYX`, and then invert it to `XYZTC` to approximate the desired ImgLib2 style (`XYCZT`). In both of these cases we miss the intended dimension order. For Numpy we return `TZCYX` instead of `TZYXC` and for ImgLib2 we return `XYZTC` instead of `XYCZT`. 

My current working solution lives in on two branches called `dimensions` on [imglyb](https://github.com/imglib/imglyb/tree/dimensions) and [pyimagej](https://github.com/imglib/imglyb/tree/dimensions). When I was running through the dimension order dance we do I was inspired by `_assign_axes` method in PyImageJ and thought we could algorithmically generate the desired dimension in the order we want the same way `_assign_axes` does and then use `numpy.transpose()`. Going from ImgPlus to Xarray now works by copying the ImgPlus data into a numpy array (in the ImgLib2 style), obtaining the dimension info (_i.e._ the labels) from the ImgPlus and then doing some fun if statements to determine what dimensions are present and what order they should be in. Converting from Xarry to Dataset works more or less the same way, read the dimension info and do some fun logic to output the order and `transpose()` the data. Overall I found it easier to deal with dimension re-ordering with `Xarray/Numpy.transpose()` as opposed to copying data backwards which can be confusing.

Here's what works:
- [x] Dataset to Xarray
- [x] ImgPlus to Numpy
- [x] Xarray to Dataset
- [ ] Numpy to Dataset/ImgPlus (no dimension order info -- so up to the user?)

Some questions:
- Is this less performative than what we currently do? My understanding is that `transpose()` makes a copy to transpose data.
- If it is, would re-ordering data in Java land be better?

To do:
- [ ] Refactor the code
- [ ] pytest fails -- I need to update up the dimension output expectations for tests.

**Comment by imagejan** [comment]
Isn't the equivalent of a numpy array a `RandomAccessibleInterval`, i.e. without any axis information? In this case, dealing with axes should be left to the caller, and no transposing or any axis reordering should be done IMHO, as it'll always result in a performance loss.

**Comment by ctrueden** [comment]
Here are my current thoughts on how the dimension order adjustments should work when converting from Java to Python.

When an image resides in shared memory between Python and Java, there is a block of memory with a bunch of values in it, in a contiguous block. When you make a numpy array object that allocates such a block of memory, you have to decide whether it's in C order or F order. For both numpy and ImgLib2, the fastest/best order in memory will align with the dimension order in that order, instead of doing any extra views or transpositions.

So, IIUC, the way things are currently done with imglyb et al., you make a numpy array the normal way, with e.g. `zeros` or whatever, and it allocates the block and internal metadata attributes to match that optimal ordering, according to the dimension order you told it.

And then when you wrap that numpy array's memory pointer to ImgLib2 using imglyb, the dimension order naturally needs to be reversed, so that ImgLib2 also iterates things in the optimal order.

This is merely due to the fact that NumPy's "fastest-moving" dimensional index is the LAST one on its list, whereas ImgLib's fastest-moving dimensional index is the FIRST one on its list. It's the SAME data, in the SAME order... just that NumPy writes the coordinates as (slow, middle, fast), and ImgLib2 writes them as (fast, middle, slow).

So therefore, the dim order needs flipping when you wrap from Python to Java—which is what imglyb does.

But then, what about the Java-to-Python direction? Right now, we copy the data, so it really doesn't matter what order we do things in, except that we want to give the user the nicest order for their environment. As stated above, on the Python/scikit-image side that optimal order is `TZYXC`, i.e. `CXYZT` in Java/ImgLib2, with any extra dimensions appended after that in their unchanged order.

Here's how we can achieve that in technical detail:

1. I wrote a function `prioritize` which takes a list of original/old axis types, and a list of axis types to prioritize in order of preference (which for us here will always be {C, X, Y, Z, T}), and returns an `int[]` index mapping *from new index to old index*. So for example, if we call this function on a dataset with axis order XYABCZT, which should become CXYZTAB, the returned axis mapping will be {4, 0, 1, 5, 6, 2, 3} e.g. the C dimension which ends up at position 0 originated in position 4 of the original/old ordering.

2. We use the axis mapping from (1) to allocate a new numpy image on the Python side, which has the desired dimensional lengths. We then wrap the numpy array to an ImgLib2 image by memory reference using imglyb as usual. ***This will reverse the dimension order.*** In the example from (1), we'll end up with a Java-side image ordered CXYZTAB, which wraps a numpy image ordered BATZYXC.

3. We take our original Java-side ImgLib2 image and permute its axes around until it aligns with our target order—e.g. BATZYXC. I wrote another function for this, `reorganize`, which takes the original image together with the index map computed in (1).

4. We copy our reorganized image from (3) onto the destination wrapped image from (2), using `net.imagej.util.Images.copy`.

The end result is a numpy array with data correctly copied from the original Java image, and in the ideal dimension order.

Here is the completed thing: ctrueden/sandbox@dee2077

If you like it, I can migrate the methods:

* `Dataset reorganize(Dataset dataset, int[] new2old)`
* `int[] prioritize(AxisType[] axisTypes, AxisType[] preferredAxisTypes)`
* `<T extends Type<T>> ImgPlus<T> reorganize(ImgPlus<T> image, int[] new2old)`

into the `net.imagej.util.Images` utility class.

**Comment by ctrueden** [comment]
@elevans Did you get a chance to play with the code I wrote yet? Does it work as is for you, and if so, do you agree that putting it in imagej-common in the `net.imagej.util.Images` class makes sense?

**Comment by elevans** [comment]
I'm playing with it today and will report back. Just from reading the code it looks like this will work nicely! I'm not 100% sure yet but putting this in `net.imagej.util.Images` (provided it works as we want it to) makes the most sense to me.
