### ISSUE TITLE
Add a __version__ attribute for dynamic version introspection

### ISSUE THREAD

**Issue by gselzer** [imagej/pyimagej#187]
Many modules, like [numpy](https://stackoverflow.com/questions/1520234/how-do-i-check-which-version-of-numpy-im-using) support this.

Under the hood, Numpy uses [Versioneer](https://github.com/python-versioneer/python-versioneer) (they call it [here](https://github.com/numpy/numpy/blob/ae13307732b430daa56c6a85ab56006611a5b6ba/numpy/__init__.py#L419))

**Comment by ctrueden** [comment]
Thanks @gselzer for researching that!

**Comment by ctrueden** [comment]
It looks like PyImageJ already had a `__version__` attribute since 508507c8e55e9c2fd4be6a5175c5c901814a07ca back in 2020. But with 1bab722f431d43a7ac3073d913b84807c379d7f0, @gselzer improved it to use scyjava's snazzy `get_version` function, which is a nice way to keep things DRY and respect PEP8's restrictive module-level dunders rule.
