### ISSUE TITLE
"Non-image windows" unfound when ij.py.run_script(name)

### ISSUE THREAD

**Issue by tdhellemmes** [imagej/pyimagej#215]
Hi, 
I'm currently trying to make my "ijm" macro run but it always crashes with this error message "No window with the title "Results" found." (same with "Log" when I have one). I guess it's something about "non-image windows".
```python
import imagej
ij = imagej.init("/Applications/Fiji.app")
macro = """ 
pathway="/Users/thibault/Desktop/Treated_images/" condition="1" increment="3"
open("/Users/thibault/Desktop/Test.tif");
name=getTitle();
Stack.getDimensions(width, height, channels, slices, frames);
run("Split Channels");
for (i = 1; i <= channels; i++) {
	selectWindow("C" + i + "-" + name);
	rename("C"+i);
}
getVoxelSize(width, height, depth, unit);
selectWindow("C1");
	run("Duplicate...", "title=[Stack stat.] duplicate")
	run("Set Measurements...", "area bounding redirect=None decimal=3");
	run("Measure");
	selectWindow("Results");
		i = 1;
		run("Read and Write Excel", "file=["+pathway+"Cond"+condition+"_"+increment+".xlsx] sheet=Stack " +i);
		Table.rename("Results", "Table_Stack_measure");
"""
language_extension ='ijm'
result_script = ij.py.run_script(language_extension, macro)
print("Done")
```
Do you have any idea of what could be the reason?
Thank you for your help,

**Comment by ctrueden** [comment]
@tdhellemmes Probably, this cannot work in [headless mode](https://pyimagej.readthedocs.io/en/latest/Headless.html). Use of original ImageJ functions while headless has [some limitations](https://pyimagej.readthedocs.io/en/latest/11-Working-with-the-original-ImageJ.html#original-imagej-in-headless-mode), and accessing the Results and Log windows is probably not possible.

You have a couple of options:
* Run in interactive mode on a non-macOS platform.
* Run [inside an Xvfb frame buffer](https://pyimagej.readthedocs.io/en/latest/Headless.html#using-pyimagej-with-xvfb), maybe inside a Docker image or VM on your macOS machine, so that you have access to Linux.

I know these options are convoluted and frustrating, but it's a fundamental limitation with the original ImageJ. The best way forward is ultimately to stop using that macro, in favor of a script that does not use original ImageJ functions. From your macro, it looks like all you are doing is making some measurements, so you could switch to ImageJ2/Ops pretty easily; see [this walkthrough in the PyImageJ use cases](https://pyimagej.readthedocs.io/en/latest/Classic-Segmentation.html#segmentation-workflow-with-imagej2) for a similar example that also does segmentation.
