### ISSUE TITLE
Petition for Discussions Tab

### ISSUE THREAD

**Issue by jmdelahanty** [imagej/pyimagej#229]
Hello! I just saw stuff about this cool new toolset online and have some questions about things that I don't want to blow up the issues with. Could you enable Discussions so a forum could be made? Or should I just hop onto the zulip chat for things? Thanks!

**Comment by ctrueden** [comment]
For discussions, https://forum.image.sc is most preferred; see https://imagej.net/discuss/chat for rationale why. But if you are expecting to be very "chatty" then using https://imagesc.zulipchat.com is also OK, especially if the discussion is more development-oriented rather than user support. :smile:

Also, don't worry about filing a few issues here. If you have a series of questions that are all related, then using a single issue here for all of them is fine. Or if they are really separate questions/concerns, then multiple issues is also good.
