### ISSUE TITLE
Running customized plugin in ImageJ "locally" on Colab

### ISSUE THREAD

**Issue by CanYing0913** [imagej/pyimagej#235]
Following [this post](https://forum.image.sc/t/running-local-plugin-on-colab/73414), I successfully downloaded Maven & OpenJDK (Linux version since Colab is on Linux) to Colab and set the corresponding environment variables (`JAVA_HOME` points to the corresponding jdk folder) and maven `bin` folder added to `PATH` (running `mvn -v` successfully prints out version). I used `mamba` to install `pyimagej` so I assume all required dependencies are installed.

However, the problem persists that I cannot run my customized plugin, `Image_Stabilizer_Headless`. It always throws:
```
->ij.IJ.run(imp, "Image Stabilizer Headless",
       "transformation=" + Transformation + " maximum_pyramid_levels=" + str(MAX_Pyramid_level) +
       " template_update_coefficient=" + str(update_coefficient) + " maximum_iterations=" + str(MAX_iteration) +
       " error_tolerance=" + str(error_tolerance))
[java.lang.Enum.toString] Plugin or class not found: "Image_Stabilizer_Headless"
(java.lang.ClassNotFoundException: Image_Stabilizer_Headless)[java.lang.Enum.toString] 
```
So does pyimagej support customized plugin on Colab? I have to initialize `ij` as a local installation since my plugin in not on the library. My Colab notebook is [here](https://colab.research.google.com/drive/1dpxLemlpCTVIzbqaAlLplfwBp5AMMnDL?usp=sharing) if anyone want to replicate the error. It downloads required python code from my repo and use mamba to add dependencies. Any tiff file can serve as the input.

If it cannot work this way, is there any workaround I can manage to run my plugin on Colab? Thank you.

**Comment by ctrueden** [comment]
>  I suggest to also include setup instructions for virtualized environment (e.g. Colab, containers, or computing machine over AWS, Azure and GCP).

@CanYing0913 Good idea. I have beefed up the instructions for Google Colab based on the findings of our recent discussion; see 7ba9df6ee9278255be0c4f6c1ea85c2db109062e. I did not test the last cell that opens Blobs and runs Filter Rank on it... if you have time to test it, that would be appreciated, although I think it's already good enough to give people an idea of the path to success.

I do not have time right now to explore other approaches like AWS; IMHO it's really outside the scope of the PyImageJ project to hold people's hands through setting those up. PyImageJ is just a Python program depending on OpenJDK, so any environment where you can get those running should be usable, but each platform might be a little different. All of that said: if you write detailed instructions for setting up PyImageJ in any of those specific scenarios and want to contribute it to the documentation via a pull request, we'd certainly be interested in merging it, since as you say it could help others.
