### ISSUE TITLE
init using 'gui' not working and interactive window changes between Java and ImageJ

### ISSUE THREAD

**Issue by leosilvero9** [imagej/pyimagej#236]
I have started experimenting with the python wrapper for ImageJ and I have come across a couple of issues:

when initialising with the following:
```
ij=imagej.init(mode='gui')
```
ij appears to be an empty item.
It works fine if I initialise as 'interactive'.

Another issue I see with the code below:
```
ij=imagej.init(mode='interactive'
jimage = ij.io().open("myimage.fits")
ij.ui().show(dataset)
```
is that the window that opens to show my image is most of the times a Java window. However occassionally, an ImageJ window will open that will have my image. The ImageJ window seems to respond better when I try to interact with it (zooming in and out).

Any ideas what's going on here? How can I always have my interactive window set to ImageJ and how can I initialise imageJ with gui?

**Comment by ctrueden** [comment]
@leosilvero9 Sorry your questions slipped through the cracks till now!

For interactive mode, try adding `ij.ui().showUI()` before showing your image:
```python
ij = imagej.init(mode='interactive')
ij.ui().showUI()
dataset = ij.io().open("myimage.fits")
ij.ui().show(dataset)
```

For GUI mode, I'm not sure what you mean by "empty item", but if you mean that it blocks, then that is by design. This mode is primarily to accommodate macOS. What operating system are you using? If not macOS, then always using interactive mode should work fine.
