### ISSUE TITLE
PyImageJ 1.4.1 breaks Jupyter Notebook Debugging in VScode

### ISSUE THREAD

**Issue by fschiffers** [imagej/pyimagej#256]
I'm crossposting this from here ( https://github.com/microsoft/vscode-jupyter/issues/13227 ) as I believe this might be more of a PyImageJ issue than a VScode Jupyter Issue.

**What is the problem:** After initialization with ImageJ the Jupyter Notebook, doesn't know the ipykernel anymore

**Expected Behavior:**

I expect the Debugging / Ipykernel version to work after ImageJ is initialized for any PyImageJ version

**Actual Behavior:**

For PyImageJ 1.4.1 the IpyKernel is no longer found after ImageJ is initialized. It seems to wot work with ImageJ 1.3.2.

Hence, downgrading PyImageJ is temporarily solution to this problem.

**How to reproduce**

1. Windows environment with Visual Studio Code (non insider version)
2. Install PyImage 1.4.1

Run the following cell blocks

1. First Cell block
`from datetime import datetime

def test_function_for_debug():
    now = datetime.now()

    current_time = now.strftime("%H:%M:%S")
    print("Current Time =", current_time)
    return current_time`

2. Test the function (print output should work)
`test_function_for_debug()`

3. Initialize ImageJ
`import imagej
#ij = imagej.init('sc.fiji:fiji',headless=False)
#ij = imagej.init(headless=False)
ij = imagej.init('sc.fiji:fiji')
`

4. Now the print output doesn't work anymore and Ipykernel cannot be found / debugging no longer works
`test_function_for_debug()`

**Comment by ctrueden** [comment]
Thanks for the report, @fschiffers, and sorry for the delay in addressing it. We have noticed this problem as well while updating the PyImageJ documentation. It happens in plain Jupyter notebook as well as VS Code. The cause is [these two lines of code from scyjava](https://github.com/scijava/scyjava/blob/1.9.0/src/scyjava/_script.py#L54-L55), which PyImageJ 1.4.1 triggers now by default to enable the SciJava Python script language. I have pushed a change (scijava/scyjava@fbf8cb574bc797397416cc13f4da7e10b4fed4b8) that might fix the problem—still untested. Tangentially: it appears the stdout handling of the Python script language is broken regardless (both before and after that fix), which you can see by adding a `print` statement to the `it/scripting.py` and running it.

**Comment by elevans** [comment]
@ctrueden and @fschiffers I can confirm that https://github.com/scijava/scyjava/commit/fbf8cb574bc797397416cc13f4da7e10b4fed4b8 resolves this issue and I can print again using the latest `scyjava`.
