### ISSUE TITLE
Add support for tables / Pandas dataframes

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#27]
Pyimagej should convert and/or wrap between `org.scijava.table.Table` and Pandas dataframes.

**Comment by hadim** [comment]
Done with https://nbviewer.jupyter.org/gist/hadim/a7492029af81ad9fe974953ab4bf8e8b

Let me know where is the best place to put this: `scyjava` or `pyimagej`.

Also what API do you want? Automatic conversion when Pandas or Table object is detected?

**Comment by ctrueden** [comment]
I think `scyjava` makes more sense! Thanks!!

**Comment by ctrueden** [comment]
I was going to comment that maybe it makes sense also to wrap a pandas dataframe as an ImgLib2 image. But I guess you can already do that by [expressing the dataframe as a numpy array](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html#pandas.DataFrame.values) first?

**Comment by hadim** [comment]
I don't think anyone will store an image in a Pandas DataFrame, it just doesn't make sense. Also, a DataFrame is a Numpy array under the hood so as you said it's already possible to do it.

**Comment by imagejan** [comment]
How about dataframes with [MultiIndex](http://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html) axes (as they're used e.g. in [DeepLabCut](https://github.com/AlexEMG/DeepLabCut/search?q=MultiIndex&unscoped_q=MultiIndex))?

@hadim are those supported by your converters? Is this a standard use of pandas dataframes that should be covered?

**Comment by hadim** [comment]
Good point. MultiIndex is not supported at the moment. I guess the only way would be to add one column per Index when doing Pandas -> Table and add an option to specify which column should be treated as an Index when doing Table -> Pandas.

Setting/removing Index is super easy in Pandas: `df.set_index(['column_1', 'column_2'])` or `df.drop_index()`.

I would suggest merging the PR first that add the basic Pandas <-> Table conversion. I would look into the MultiIndex support later.

**Comment by imagejan** [comment]
Another option would be to (somehow) support something similar to MultiIndex in SciJava tables. But I have no idea how commonly used these features are in the Python world, and whether it'd be worth the effort to support them in SciJava. Should we open an issue in [`scijava/scijava-table`](https://github.com/scijava/scijava-table/issues)?

**Comment by hadim** [comment]
I used MultiIndex extensively a few years ago during my Ph.D. and it's very useful. Keep in mind that MultiIndex, while a powerful Pandas feature, makes some of the operations on DataFrame much slower than with a simple Index (no benchmark to show only my experience).

And again the usual Pandas workflow is to drop indexes when not needed and set it when needed. Those operations can create a new DataFrame or be performed "in-place".

That being said, MultiIndex is probably not widely used (here again more a feeling than statistics), just because most of the time you can achieve what you want by only using Index. Also, serialization to CSV or Excel is trickier when using MultiIndex.

As for SciJava, I don't see anything wrong adding this kind of feature to it. Then we could have a 1:1 converter with Pandas.

I don't think a Scyjava MultiIndex would be useful to me (at least for the moment), so I am not sure I'll have time to look into it.

**Comment by ctrueden** [comment]
Addressed in scijava/scyjava#9, thanks to @hadim!
