### ISSUE TITLE
Redirecting stdout of Fiji plugins

### ISSUE THREAD

**Issue by jluethi** [imagej/pyimagej#35]
Is there a way to redirect the stdout of a Fiji plugin? I'm using the 'Grid/Collection stitching' plugin and want to get the parameters of the transformation out. They are printed when the plugin is run in the following way:

```
ij = imagej.init('/Applications/Fiji.app')
plugin = 'Grid/Collection stitching'
            args = {'type': '[Filename defined position]', 'order': '[Defined by filename         ]',
                    'grid_size_x': '3', 'grid_size_y': '3', 'tile_overlap': '8', 'first_file_index_x': str(index_x),
                    'first_file_index_y': str(index_y), 'directory': img_path,
                    'file_names': 'Tile_{yyy}-{xxx}-000000_0-000.tif', 'output_textfile_name': 'TileConfiguration.txt',
                    'fusion_method': '[Intensity of random input tile]', 'regression_threshold': '0.15',
                    'max/avg_displacement_threshold': '0.20', 'absolute_displacement_threshold': '0.30',
                    'compute_overlap': True, 'computation_parameters': '[Save memory (but be slower)]',
                    'image_output': '[Write to disk]'}
ij.py.run_plugin(plugin, args)
```

Example excerpt from the print:
```
Finished registration process (12645 ms).
Tile_002-010-000000_0-000.tif: [3,3](AffineTransform[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]) 0.0
Tile_002-011-000000_0-000.tif: [3,3](AffineTransform[[1.0, 0.0, 3744.0], [0.0, 1.0, 136.0]]) 0.0
Tile_002-012-000000_0-000.tif: [3,3](AffineTransform[[1.0, 0.0, 7398.0], [0.0, 1.0, 265.0]]) 0.0
Tile_003-010-000000_0-000.tif: [3,3](AffineTransform[[1.0, 0.0, -20.0], [0.0, 1.0, 4087.0]]) 0.0
Tile_003-011-000000_0-000.tif: [3,3](AffineTransform[[1.0, 0.0, 3718.0000000000005], [0.0, 1.0, 4210.0]]) 4.482534314920437E-26
Tile_003-012-000000_0-000.tif: [3,3](AffineTransform[[1.0, 0.0, 7373.0], [0.0, 1.0, 4257.0]]) 0.0
Tile_004-010-000000_0-000.tif: [3,3](AffineTransform[[1.0, 0.0, -91.99999999999955], [0.0, 1.0, 7808.0]]) 0.0
Tile_004-011-000000_0-000.tif: [3,3](AffineTransform[[1.0, 0.0, 3655.0], [0.0, 1.0, 7914.0]]) 0.0
Tile_004-012-000000_0-000.tif: [3,3](AffineTransform[[1.0, 0.0, 7329.0], [0.0, 1.0, 8025.0]]) 2.0679515313825692E-25
Writing registered TileConfiguration: [REDACTED]
Fuse & Write to disk (into directory [REDACTED]
Finished fusion (26801 ms)
```

I need to get the details after the AffineTransform. I have tried standard python stdout redirecting, but that does not catch the stdout of ImageJ. It is still printed and the f variable that is supposed to catch the print info is empty.

```
ij = imagej.init('/Applications/Fiji.app')
plugin = 'Grid/Collection stitching'
f = io.StringIO()
with contextlib.redirect_stdout(f):
    ij.py.run_plugin(plugin, args)

stitching_output = f.getvalue()
print('Catching Fiji print:')
print(stitching_output)
ij.py.run_plugin(plugin, args)
```

I have read that redirecting stdout of code of a different language is more complicated, see example here for C code being run in python: https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/

How is the Java stdout handled and sent to python? Does anyone have an idea how I could redirect that to a variable in python? Or any other approach to catch this information from the plugin?

**Comment by ctrueden** [comment]
@jluethi The SciJava framework upon which ImageJ is built has a `ConsoleService` for listening to stdout and stderr. Here is an example script illustrating how you would link into it from Python:

<details><summary>listen-to-java-console-output.py</summary>

```python
# Initialize ImageJ.
import imagej
ij = imagej.init('/Applications/Fiji.app')

# Define an OutputListener.
from jnius import PythonJavaClass, java_method
class MyOutputListener(PythonJavaClass):
    __javainterfaces__ = ['org/scijava/console/OutputListener']

    @java_method('(Lorg/scijava/console/OutputEvent;)V')
    def outputOccurred(self, e):
        source = e.getSource().toString()
        output = e.getOutput()
        print('\n[OUTPUT]\n\tsource = {}\n\toutput = {}'.format(source, output))

# Instantiate our OutputListener.
l = MyOutputListener()

# Register it with ImageJ.
ij.console().addOutputListener(l)

# Test it!
from jnius import autoclass
System = autoclass('java.lang.System')
System.out.println('Hello world')
```

</details>

However, I would _strongly advise you_ not to rely on particular output for your program to behave correctly. Things printed to stdout and stderr should be considered incidental, and subject to change at any time. Your program could break when the plugins are updated later.

In the case of the 'Grid/Collection stitching' plugin, would it work to parse the `TileConfiguration.txt` afterward? That file is in a defined format that won't change in the future.

**Comment by jluethi** [comment]
@ctrueden Thank you for the quick and helpful feedback and the good idea of using the TileConfiguration.registered.txt file output. This makes potential parallelization a bit harder, as there could be multiple versions of this file, but it seems like a more stable approach than the print readout. I'll be going with that 👍

**Comment by imagejan** [comment]
@jluethi you should also be able to interact with the stitching API on a lower level to get the desired values from the TranslationModel directly:

```java
ArrayList<ImagePlusTimePoint> tiles = CollectionStitchingImgLib.stitchCollection(elements, params)
```

I can share some code if that would be of interest to you.

**Comment by jluethi** [comment]
@imagejan Cool, this sounds very interesting! Do you have some example code for this? I can't quite follow what the "elements" variable is in the code line you showed.

Can I use this kind of call to get both the stitched image as well as the translational information?

Also, can I do any of that without using a local Fiji installation? I tried to initialize with the command below to make it more reproducible and independent of changes to the local Fiji installation, but that doesn't seem to work:
`ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10')`

It gives me the following error message:
`Unrecognized command: "Grid/Collection stitching"`
I saw that you only test plugin calls with local installations in the unittests, so this makes sense. Would the lower level API call have the same restrictions of only running with the local Fiji application or could it use the reproducible initialization?

**Comment by imagejan** [comment]
@jluethi the `elements` is an `ArrayList<ImageCollectionElement>`, something quite deep into the stitching API, but fortunately easy to create.

I just made the repository containing some sample code (a work in progress) public, so here is the relevant static method:

https://github.com/fmi-basel/faim-ij2-visiview-processing/blob/14b77367b635e19a648565457098393be76f1393/src/main/java/ch/fmi/visiview/StitchingUtils.java#L61-L109

In order to get a stitched image, you'll additionally have to call `Fusion.fuse` or this other static method:

https://github.com/fmi-basel/faim-ij2-visiview-processing/blob/14b77367b635e19a648565457098393be76f1393/src/main/java/ch/fmi/visiview/StitchingUtils.java#L111-L130

If you (or anyone else) think these methods should live in some consumable component, I'll be happy to do one of the following:

* migrate them upstream into [`fiji/Stitching`](https://github.com/fiji/Stitching)
* deploy the `faim-ij2-visiview-processing` artifact (or a renamed version of it) to `maven.scijava.org`

---

Regarding calling a plugin via `ij.py.run_plugin` in a maven-initialized installation, I'll have to defer this question to @ctrueden.

**Comment by ctrueden** [comment]
> can I do any of that without using a local Fiji installation? I tried to initialize with the command below to make it more reproducible and independent of changes to the local Fiji installation, but that doesn't seem to work:
> ```python
> ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10')
> ```
> It gives me the following error message:
> ```
> Unrecognized command: "Grid/Collection stitching"
> ```

Yes, I knew about that problem, but had not filed an issue yet. I have now done so: #36. TL;DR: It is a limitation of ImageJ1, that could potentially be worked around with effort.

**Comment by jluethi** [comment]
@imagejan Thank you very much, this looks very interesting. This is the pairwise stitching, right? Can it do a global optimization similar to the Grid/Collection stitching? I didn't see any inputs like the regression threshold or the displacement thresholds that Grid/Collection stitching makes available.

Also, is there a way to call this via pyimagej from python? I'm not really familiar with Java and am thus trying to keep the program in python.

Finally, if I can call this from python somehow: Is it possible to keep the image in java so that I can run operations on it like changing the pixel size and saving from imageJ? I tried getting the current image with the Window Manager to save it:
```
from jnius import autoclass
WindowManager = autoclass('ij.WindowManager')
stitched_img = WindowManager.getCurrentImage()
ij.io().save(stitched_img, '/Users/Joel/Desktop/test2.png')
```
But running the ij.io().save on this just fails silently (no error message, but no file saved either). On the other hand, when I use this to get the image into a numpy array, I can run:
```
stitched_img_python = ij.py.from_java(stitched_img)
cv2.imwrite(str(output_path / output_filename), stitched_img_python.astype('uint16'))
```
I get the image fine (but, because it goes to a numpy array, I loose the image metadata and I can't find a library that can reasonably edit exif data of pngs via python)

**Comment by imagejan** [comment]
@jluethi that sounds like a use case that could be of interest to a more general audience. Would you mind opening a topic on the forum about this? https://forum.image.sc/tags/pyimagej

I don't have sufficient experience with pyimagej yet to answer your questions, but would be interested in learning this, too.

**Comment by ctrueden** [comment]
> is there a way to call this via pyimagej from python?

You can include additional artifacts in the `imagej.init(...)` call using the `+` symbol:
```python
ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10+ch.fmi:faim-ij2-visiview-processing:0.0.1')
```
But this will only work after @imagejan releases version 0.0.1 of that code, deploying it to the SciJava Maven repository.

Alternately, you can clone the [fmi-basel/faim-ij2-visiview-processing](https://github.com/fmi-basel/faim-ij2-visiview-processing) repository and check out the `dev ` branch and build it yourself (`mvn clean install`) and then copy the resultant `target/faim-ij2-visiview-processing-0.0.1-SNAPSHOT.jar` artifact into your local Fiji installation and wrap that as you have been doing.

Either way, you would then `autoclass` the `StitchingUtils` class from Python and invoke the methods you want.

A third option would be to cut-and-paste-and-adapt the code you want from `StitchingUtils` directly into Python. This has the advantage of being fully customizable, but the disadvantage of lots more code on the Python side that has to go through pyjnius.

> running the `ij.io().save` on this just fails silently

There is probably an issue with using ImageJ1 `ImagePlus` images vs. ImageJ2 images like `Dataset`, `Img`, `RandomAccessibleInterval` and friends. The `ij.io().save(...)` call is designed to take an ImageJ2 image. There are a couple of different things that might avoid the issue. For example:

```python
from jnius import autoclass
WindowManager = autoclass('ij.WindowManager')
stitched_img = WindowManager.getCurrentImage()
ij.py.to_dataset(stitched_img)
```
This might work, but this A) relies on the `WindowManager` returning a non-null current image, which might be an issue if you are running in headless mode; and B) does a second conversion from IJ1->IJ2 even though internally, one may have already been done by the legacy layer.

Or:
```python
active_display = ij.imageDisplay().getActiveImageDisplay()
stitched_dataset = ij.imageDisplay().getActiveDataset(active_display)
ij.py.to_dataset(stitched_dataset)
```
Which uses ImageJ2 current way to obtain the active dataset, rather than going through ImageJ1.

I did not test either of the above just now though, so if neither way works, I can dig some more to find out why not.

**Comment by ctrueden** [comment]
> that sounds like a use case that could be of interest to a more general audience.

I agree; much of the stuff discussed in this thread above might make good sense as part of the pyimagej documentation—either a recipes section, or better, as a Jupyter notebook. We could augment the existing one in imagej/tutorials, but it's already rather long, heterogenous, unwieldy. Maybe it's time to split up the Python stuff into its own folder with multiple notebooks. I don't have time. @jluethi would you have time and interest?

**Comment by jluethi** [comment]
Thanks @ctrueden , `stitch_image_imagej2 = ij.py.to_dataset(stitched_img)` works and is saved afterwards. 
Concerning documentation: I'm happy to help, but I don't really have the overview & understanding of the imagej api to really document it in broader terms, every new api I want to call takes me ages to actually figure out and the gracious help from both of you. But I can document the workflow for doing the stitching via python and saving the results. Unfortunately, my current knowledge doesn't go much further. Let me know if creating a notebook for this example is useful to you for documentation, then I'll make one.

@imagejan Thanks for the suggestion, I didn't know this forum. I opened a topic there with some questions on calling other imageJ APIs:  https://forum.image.sc/t/using-imagej-functions-like-type-conversion-and-setting-pixel-size-via-pyimagej/25755

**Comment by ctrueden** [comment]
I think the original issue—redirecting Fiji's stdout to Python—was answered above. Please reopen if not.
