### ISSUE TITLE
Throw exceptions if ij_dir does not exist

### ISSUE THREAD

**Issue by hanslovsky** [imagej/pyimagej#4]
`[imagej.init(ij_dir)](https://github.com/imagej/imagej.py/blob/master/imagej/imagej.py#L188)` returns without failure when an invalid path is specified as Fiji.app dir. This is confusing for users who do not have any Java knowledge and do not specify a valid `ij_dir`. `imagej.init` should throw an exception in these cases. Possible options are:
 - Check if `ij_dir` exists and is directory, throw otherwise
 - Check if `ij_dir` exists and is directory, and contains at least `jars` directory, throw otherwise
 - Check if [`num_jars`](https://github.com/imagej/imagej.py/blob/master/imagej/imagej.py#L200) is greater than 0, throw otherwise

Maybe it is best to add all these checks with specific exceptions, e.g.
 - `ij_dir` does not exist
 - `ij_dir` exists but does not seem to be valid `Fiji.app` directory
 - did not find any jars in `ij_dir`.

**Comment by ctrueden** [comment]
With 18bff0c54415079b3771d15741c4eeda31edd2bb, guarding against edge cases has changed. Still should be done, but must be done differently than described above.

**Comment by imagejan** [comment]
Currently, the check for file paths (if it's *not* a directory) matches Unix-style paths only:

https://github.com/imagej/pyimagej/blob/f6eca56ed2e288097ba45abef6046667c5d5ed20/imagej/__init__.py#L142-L146

We should improve this to also match Windows-style file paths, as otherwise it will fall through to the `else` clause, treating the argument as a version identifier.

**Comment by ctrueden** [comment]
The endpoint reasoning logic is now pretty robust, addressing this issue. We also fixed some bugs:

* e3ba8a4a6b036426429663edccb0ffdb70bbf3a1
* eb025a2037f9923a7fb230b5276ee22255a46fa7
* bfd2d120df6abc4afba40b171cd2c14c9f666cd2
*
