### ISSUE TITLE
Improve installation instructions?

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/pyimagej#45]
Hey @ctrueden ,

I'm just installing pyimagej on ubuntu 18.04 and this time, I read the right installation instructions 
from [here](https://github.com/imagej/pyimagej):
```
conda config --add channels conda-forge 
conda install pyimagej openjdk=8
```

Together with your suggestion from [here](https://github.com/imagej/pyimagej/issues/38#issuecomment-524901808) it works nicely:
```
conda create -n imagej pyimagej openjdk=8
conda activate imagej
```

Furthermore, to make some of the examples run, it is necessary to install sk-image:
```
conda install scikit-image
```

Wouldn't it make sense to put these lines together in the readme or in a dedicated installation script?

I hope that helps!

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Furthermore, when googling for pyinagej, one ends up [here](https://pypi.org/project/pyimagej/). That website says 'pip install pyimagej' is the way to go. Is it possible to clarify that?

Cheers,
Robert

**Comment by ctrueden** [comment]
Improvements committed: 1feb0a817577e64c1b2c939fa8a6f1bd0e62bea9,  4d87a074a91d42a5e250c85a74ea5fd3439bc864,  31fe70b9f51c9b9cf7bb96381906697d7b56a1b6

> Is it possible to clarify that?

The page on PyPI displays whatever the `README.md` is at the time of last release. So you'll see that it matches [this version](https://github.com/imagej/pyimagej/blob/0.4.0/README.md). Since then, the README has indeed been clarified (d155fcb598bc6e38aa4add0af253430bae8ae040) to recommend conda more explicitly. The next time we push a release of pyimagej to PyPI, the README there will change accordingly.

Please take a look at the [latest README](https://github.com/imagej/pyimagej/blob/master/README.md) and feel free to file PRs improving it further.

> Wouldn't it make sense to put these lines together in the readme or in a dedicated installation script?

scikit-image is not required to install pyimagej. It is just one (of many) useful packages you can mix in. Therefore, it should not be lumped into the standard recommended one-liner installation. I added it as an aside (4d87a074a91d42a5e250c85a74ea5fd3439bc864).
