### ISSUE TITLE
imagej.init() pyjnius.jar not found error in Linux

### ISSUE THREAD

**Issue by flowernert** [imagej/pyimagej#48]
# Environment
Linux Mint 19.2 64 bits
python 3.7.3 anaconda
pyimagej installation using pip in an activated virtualenv

# Problem description
After installing the pyimagej package using pip in my activated virtual environment, I tried to import and initialize like in the documentation.
I got an error related to pyjnius.jar not been able to be found and being required by scyimage.jar
```
import imagej
ij = imagej.init('/Applications/Fiji.app')
```
gives the following output.
```
Added 394 JARs to the Java classpath.
Unable to import scyjava: pyjnius JAR not found.
Traceback (most recent call last):
  File "/home/flo/bin/anaconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-0f50100f883c>", line 1, in <module>
    ij = imagej.init("/home/flo/bin/Fiji.app")
  File "/home/flo/bin/anaconda/lib/python3.7/site-packages/imagej/imagej.py", line 70, in init
    import imglyb
  File "/home/flo/bin/pycharm-anaconda-2019.2.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/flo/bin/anaconda/lib/python3.7/site-packages/imglyb/__init__.py", line 38, in <module>
    config, _ = _init_jvm_options()
  File "/home/flo/bin/anaconda/lib/python3.7/site-packages/imglyb/__init__.py", line 33, in _init_jvm_options
    import scyjava
  File "/home/flo/bin/pycharm-anaconda-2019.2.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/flo/bin/anaconda/lib/python3.7/site-packages/scyjava/__init__.py", line 142, in <module>
    raise ImportError('Unable to import scyjava dependency jnius.')
ImportError: Unable to import scyjava dependency jnius.
```

**Comment by flowernert** [comment]
# Investigation
I tried to import the jnius library in a python console and had an error because $JAVA_HOME was not defined. It is unrelated to the current issue but  needed to be fixed as well.
By debugging scyjava/__init.py__ I've been able to see that the pyjnius.jar is looked up in the venv/share/pyjnius directory, which didn't exist.

I investigated in my anaconda installation site-packages and found out that the _jnius_ folder doesn't contain a jar but a java source file and its bytecode counterpart (NativeInvocationHandler).

# Workaround
0. (unrelated) I set up $JAVA_HOME to my java installation directory and added its bin subdirectory to the $PATH.
1. I generated a .jar from the NativeInvocationHandler.class file in my anaconda installation at
$CONDA_HOME/lib/python3.7/site-packages/jnius/src/org/jnius/NativeInvocationHandler.class
`jar -c NativeInvocationHandler.class > pyjnius.jar`
2. Then I placed in my venv/share/pyjnius directory the jar created at step 1

Finally I had a last error that appeared after these steps, related to maven not being found by the jgo.py package.

3. I installed maven on my machine
`sudo apt-get install maven`

And then calling `imagej.init('/Applications/Fiji.app')` works (yielding a few warnings though)

**Comment by ctrueden** [comment]
@flowernert It is strongly recommended to install pyimagej from conda-forge, not using pip. See https://github.com/imagej/pyimagej/blob/master/README.md#installation

If you want to use pip instead, see [this thread](https://forum.image.sc/t/how-do-i-install-pyimagej/23189/4) for a rough guide. Many of the steps you performed are either described there, or not needed. E.g. instead of needing to create your own `pyjnius.jar`, you can download it from [here](https://anaconda.org/conda-forge/pyjnius/1.2.0/download/osx-64/pyjnius-1.2.0-py37h90b5fae_0.tar.bz2).

**Comment by flowernert** [comment]
Okay, the fact that a pip package for pyimagej exists led me to believe that I can install it without having to switch my virtual environment management, which is currently virtualenv/pip (even though my python interpreter is anaconda I prefer python environment management through these tools).

Is there anything blocking pyimagej to be installed in a virtualenv/pip rather than conda, or is it just that at the present time the package installation script is only fitted to conda ?

**Comment by ctrueden** [comment]
> thanks ctrueden :)

You're welcome. :-)

> Is there anything preventing pyimagej to be installed through an installation script in a virtualenv/pip through rather than conda

Firstly: I am not a python packaging expert. So please take anything I say in that arena with a grain of salt!

The pyimagej package is deployed to PyPI so that you _can_ install it with pip... but you need to: A) make sure you have installed the non-Python dependencies Java and Maven as well; and B) set the `JAVA_HOME` and `PYJNIUS_JAR` environment variables.

Another reason pyimagej is deployed to PyPI is because conda-forge has a convenient mechanism adapting PyPI releases to new conda-forge feedstock PRs. So releasing on both platforms is not much extra work.

Because pip/virtualenv is a Python-only paradigm (please correct me if I'm wrong), I do not see a way around requiring external installation of Java and Maven.

We do try to autodetect the Java location in cases where an `mvn` executable is on the path—the scyjava layer invokes `mvn -v` and scrapes the Java runtime path reported there. But this assumes your system is already set up for Maven to work from the CLI.

As for `PYJNIUS_JAR`, I want to eliminate the need to set this variable, ever. We can do it by deploying `pyjnius.jar` to the maven.scijava.org repository and then including it in the jgo endpoint. I filed an issue for that at scijava/scyjava#11.

@flowernert How much do you know about Python packaging? Do you see other ways we can improve the situation here?

**Comment by flowernert** [comment]
Thanks for the  detailed answer ;)

I'm really more a coder than a package builder/maintainer, but as for everything related to coding, I can lookup the necessary resources to achieve a technical goal :)

I'll check out if the several issues/dependencies at hand here (maven, pyjnius jar, java home) can be treated through a pip package install script.

If not, at least a python script downloadable on your website could help to complete the installations of dependencies not being handled by pip.

**Comment by ctrueden** [comment]
> a python script downloadable on your website could help to complete the installations of dependencies not being handled by pip.

Installing Java and Maven is a platform-dependent process. Trying to create a Python script to automate this would be full of many edge cases. Conda exists to solve these sorts of problems in a platform-independent way. I would be very reluctant to invest time in any sort of custom tooling to install non-Python dependencies just for the benefit of people too stubborn to use conda.

**Comment by FengZhiheng** [comment]
> # Environment
> Linux Mint 19.2 64 bits
> python 3.7.3 anaconda
> pyimagej installation using pip in an activated virtualenv
> 
> # Problem description
> After installing the pyimagej package using pip in my activated virtual environment, I tried to import and initialize like in the documentation.
> I got an error related to pyjnius.jar not been able to be found and being required by scyimage.jar
> 
> ```
> import imagej
> ij = imagej.init('/Applications/Fiji.app')
> ```
> 
> gives the following output.
> 
> ```
> Added 394 JARs to the Java classpath.
> Unable to import scyjava: pyjnius JAR not found.
> Traceback (most recent call last):
>   File "/home/flo/bin/anaconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-3-0f50100f883c>", line 1, in <module>
>     ij = imagej.init("/home/flo/bin/Fiji.app")
>   File "/home/flo/bin/anaconda/lib/python3.7/site-packages/imagej/imagej.py", line 70, in init
>     import imglyb
>   File "/home/flo/bin/pycharm-anaconda-2019.2.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
>     module = self._system_import(name, *args, **kwargs)
>   File "/home/flo/bin/anaconda/lib/python3.7/site-packages/imglyb/__init__.py", line 38, in <module>
>     config, _ = _init_jvm_options()
>   File "/home/flo/bin/anaconda/lib/python3.7/site-packages/imglyb/__init__.py", line 33, in _init_jvm_options
>     import scyjava
>   File "/home/flo/bin/pycharm-anaconda-2019.2.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
>     module = self._system_import(name, *args, **kwargs)
>   File "/home/flo/bin/anaconda/lib/python3.7/site-packages/scyjava/__init__.py", line 142, in <module>
>     raise ImportError('Unable to import scyjava dependency jnius.')
> ImportError: Unable to import scyjava dependency jnius.
> ```

I had the same problem
