### ISSUE TITLE
Link structures converted from Java -> Python

### ISSUE THREAD

**Issue by mpinkert** [imagej/pyimagej#73]
Currently, only structures converted from Python to Java are linked.   E.g., modifying a dataset that came from a numpy array will also change the numpy array.

The converse is not true.   Creating a Python object from a Java object will make a new Python object that is not linked to the Java object.

Changing this would require a different interface to the JVM, as this is a limitation of pyjnius (currently).

This would be a nice-to-have feature.

**Comment by hinerm** [comment]
Is this still true in Jpype..?

**Comment by ctrueden** [comment]
Still true in JPype. To go the other way requires a substantial amount of coding, to wrap a Java-side ImgLib2 image into a "numpy-array-like" structure, which could work in many Python scenarios via duck typing.

**Comment by hanslovsky** [comment]
(3) should be possible already, albeit I don't think there is a convenience method for that. Things may have changed since I was last involved with imglyb (it was still pyjnius back then), but there is/was a way to generate ImgLib2 ArrayImgs backed by native memory and you can then simply pass that pointer into a numpy array.

I have wrapped a numpy-like object into a cached cell img (3). I don't remember what exactly the object was but as long as the individual cells can be mapped to native memory, this shouldn't be too much of a challenge. It is a different story for completely arbitrary objects, though.

(4) may be challenging. When I toyed around with JNI, I found it to be terribly slow, so interaction between Java and C/Python at a per-voxel level may not work. One example that might pose a challenge is in-place addition of a wrapped ImgLib2 object into a native numpy array, e.g.
```python
native_numpy_array += wrapped_imglib2_object
```
This may be simple if the `+=` can be overwritten in the new class that represents the wrapped object. Then, the `native_numpy_array` could be temporarily wrapped as imglib2 and the `+=` could be implemented with Java only.

**Comment by ctrueden** [comment]
Since (1) is done, and (4) is effectively now done thanks to `@JImplementationFor` providing arraylike API access to JPype-wrapped `Dataset`, `Img`, `RandomAccessibleInterval`, etc., let's close this. @gselzer and I filed #202 and #203 to cover the remaining cases discussed above, which are not urgent to implement.
