### ISSUE TITLE
Return Values From Not Self-Defined Macro's

### ISSUE THREAD

**Issue by WilliamJudge94** [imagej/pyimagej#96]
I am trying to return a set of values defined inside of a Maco, which I did not write myself. This is a continuation of issue #95.

Goal: 
1) use a custom macro found [here](https://imagej.nih.gov/ij/plugins/mssim-index.html)
2) load images into ImageJ with the pyimagej module
3) use pyimagej to call the MS_SSIM_index class
4) return the contrast, luminescence, and structural scores written into the MS_SSIM_index class and can be found in the last dialogue box of the macro

```
# Running the GUI of imagej - hope to turn this into headless
import imagej
import imageio
from scyjava import jimport

ij = imagej.init("/home/will/.imagej/Fiji.app", headless=False,)
ij.ui().showUI()
WindowManager = jimport('ij.WindowManager')

# Load Image 1 
main = imageio.imread('/home/Desktop/image1.png')
ij.ui().show('main image', ij.py.to_java(main))

# Load Image 2
compare = imageio.imread('/home/Desktop/image2.png')
ij.ui().show('compare image', ij.py.to_java(compare))
    
plugin = 'MS SSIM index'
args = { 
}
results = ij.py.run_plugin(plugin, args)
print(results.getOutputs())
```

All I get is an empty array for the outputs. Inside the macro there are three variables I would like to return: structural_component, luminecence_component, and contrast_component

**Comment by imagejan** [comment]
The MS-SSIM plugin reports results in a non-canonical way, using the numeric fields of a `GenericDialog` (which is supposed to get user *input*) instead of e.g. a `ResultsTable`. I know no other plugin doing this, and I'd suggest the plugin be changed in a way that allows programmatic access to the outputs.

```
	GenericDialog results = new GenericDialog ("RESULTS: MS-SSIM Index and components");
	results.addNumericField ("Luminance comparison: ", luminance_comparison, 5, 7, "");
	results.addNumericField ("Contrast comparison: ", contrast_comparison, 5, 7, "");
	results.addNumericField ("Structure comparison: ", structure_comparison, 5, 7, "");
	if (algorithm_selection == "Zhou Wang") 
		results.addNumericField ("MS-SSIM index Zhou Wang: ", ms_ssim_index, 5, 7, "");
	else
		results.addNumericField ("MS-SSIM index Rouse/Hemami: ", ms_ssim_index, 5, 7, "");
	results.showDialog();
	results.dispose();
```

**Comment by WilliamJudge94** [comment]
This is what I originally thought, but didn't want to admit since I am unfamiliar with Java code. Would I be able to just change "GenericDialog" to "ResultsTable" and recompile the .java code into a .class?

**Comment by ctrueden** [comment]
@WilliamJudge94 Sorry no one ever got back to you on your questions. It is not as simple as changing `GenericDialog` to `ResultsTable`, unfortunately, because they have totally different APIs.

Did you find a solution? Or are you still interested in improving the MS SSIM index plugin? If you still want to make changes to this plugin, start a topic on forum.image.sc and reply back here with a link, and we will try to help you there. (That mini-project is not really related to PyImageJ anymore, so the forum is a better place to discuss.)
